version: '2'

volumes:
  docker-jenkins-home:
    driver: local

services:

  jenkins-service:
    build:
      context: .
    volumes:
      - docker-jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:8080"