version: '2'

volumes:

  highlite2-jenkins-home:
    external: true

services:

  jenkins:
    image: oliosinter/jenkins:jenkins_2.109
    volumes:
      - highlite2-jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:8080"
    env_file:
      - config.env