version: '2'

volumes:
  jenkins-home:
    driver: local

services:

  jenkins:
    image: oliosinter/jenkins:jenkins_2.109
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:8080"